---
- name: Filterliste laden
  include_vars:
    file: ignored_sockets.yml
    name: ignore_data

- name: discover_sockets.py auf Remote kopieren
  copy:
    src: discover_sockets.py
    dest: /tmp/discover_sockets.py
    mode: '0755'

- name: Sockets entdecken
  shell: "python3 /tmp/discover_sockets.py --ignore '{{ ignore_data.ignored_ports | map(attribute='socket') | join(',') }}'"
  become: true
  register: socket_raw

- name: Socketliste in strukturierte Objekte umwandeln
  set_fact:
    socket_list: "{{ socket_raw.stdout | from_json }}"
