---
- name: CSV-Datei initialisieren (TLS OK)
  copy:
    dest: /tmp/tls_results.csv
    content: "ip,port,pid,tls_version,cipher,issuer,subject,not_after,san,chain\n"
    mode: '0644'

- name: CSV-Datei initialisieren (TLS Fehler)
  copy:
    dest: /tmp/tls_errors.csv
    content: "ip,port,pid,error\n"
    mode: '0644'

- name: CSV-Daten anhängen (TLS OK)
  lineinfile:
    path: /tmp/tls_results.csv
    line: "{{ item.ip }},{{ item.port }},{{ item.pid }},{{ item.process }},{{ item.tls_version }},{{ item.cipher }},{{ item.issuer }},{{ item.subject }},{{ item.not_after }},{{ item.san }},{{ item.chain | join(';') }}"
    insertafter: EOF
  loop: "{{ tls_results }}"
  when: item.error == ""

- name: CSV-Daten anhängen (TLS Fehler)
  lineinfile:
    path: /tmp/tls_errors.csv
    line: "{{ item.ip }},{{ item.port }},{{ item.pid }},{{ item.process }},{{ item.error }}"
    insertafter: EOF
  loop: "{{ tls_results }}"
  when: item.error != ""
